
project_id = "sdeyqojklszwarfrputz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "https://oneglobaltrip.com"
additional_redirect_urls = ["https://127.0.0.1:3000", "https://oneglobaltrip.com", "https://sdeyqojklszwarfrputz.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.external.google]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"
secure_email_change_enabled = true
secure_password_change_enabled = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[functions.square-create-payment]
verify_jwt = true

[functions.square-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-marketing-email]
verify_jwt = false

[functions.send-automated-email]
verify_jwt = false

[functions.email-tracking]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.ai-travel-agent]
verify_jwt = false

[functions.visa-eligibility-ai]
verify_jwt = false

[functions.xai-chat]
verify_jwt = false

[functions.openai-realtime-token]
verify_jwt = false

[functions.conversation-title]
verify_jwt = false
