// Enhanced city to IATA code mappings with fuzzy matching support
export const CITY_TO_IATA: Record<string, string> = {
  // Major US cities
  'houston': 'IAH',
  'h-town': 'IAH',
  'space city': 'IAH',
  'dallas': 'DFW',
  'big d': 'DFW',
  'fort worth': 'DFW',
  'new york': 'JFK',
  'nyc': 'JFK',
  'new york city': 'JFK',
  'manhattan': 'JFK',
  'brooklyn': 'JFK',
  'los angeles': 'LAX',
  'la': 'LAX',
  'city of angels': 'LAX',
  'chicago': 'ORD',
  'chi town': 'ORD',
  'windy city': 'ORD',
  'miami': 'MIA',
  'magic city': 'MIA',
  'atlanta': 'ATL',
  'hotlanta': 'ATL',
  'boston': 'BOS',
  'beantown': 'BOS',
  'seattle': 'SEA',
  'emerald city': 'SEA',
  'san francisco': 'SFO',
  'sf': 'SFO',
  'frisco': 'SFO',
  'bay area': 'SFO',
  'las vegas': 'LAS',
  'vegas': 'LAS',
  'sin city': 'LAS',
  'denver': 'DEN',
  'mile high city': 'DEN',
  'phoenix': 'PHX',
  'valley of the sun': 'PHX',
  'philadelphia': 'PHL',
  'philly': 'PHL',
  'city of brotherly love': 'PHL',
  'detroit': 'DTW',
  'motor city': 'DTW',
  'minneapolis': 'MSP',
  'twin cities': 'MSP',
  'orlando': 'MCO',
  'o-town': 'MCO',
  'charlotte': 'CLT',
  'queen city': 'CLT',
  'washington': 'DCA',
  'dc': 'DCA',
  'washington dc': 'DCA',
  'baltimore': 'BWI',
  'nashville': 'BNA',
  'music city': 'BNA',
  'austin': 'AUS',
  'atx': 'AUS',
  'keep it weird': 'AUS',
  'san antonio': 'SAT',
  'alamo city': 'SAT',
  'san diego': 'SAN',
  'america finest city': 'SAN',
  'portland': 'PDX',
  'rose city': 'PDX',
  'salt lake city': 'SLC',
  'slc': 'SLC',
  
  // International cities
  'london': 'LHR',
  'big ben': 'LHR',
  'england': 'LHR',
  'paris': 'CDG',
  'city of lights': 'CDG',
  'city of love': 'CDG',
  'madrid': 'MAD',
  'barcelona': 'BCN',
  'rome': 'FCO',
  'eternal city': 'FCO',
  'amsterdam': 'AMS',
  'venice of the north': 'AMS',
  'berlin': 'BER',
  'munich': 'MUC',
  'frankfurt': 'FRA',
  'zurich': 'ZUR',
  'vienna': 'VIE',
  'brussels': 'BRU',
  'milan': 'MXP',
  'istanbul': 'IST',
  'dubai': 'DXB',
  'city of gold': 'DXB',
  'tokyo': 'NRT',
  'singapore': 'SIN',
  'lion city': 'SIN',
  'sydney': 'SYD',
  'harbour city': 'SYD',
  'toronto': 'YYZ',
  'vancouver': 'YVR',
  'mexico city': 'MEX',
  'cdmx': 'MEX',
  'mumbai': 'BOM',
  'bombay': 'BOM',
  'delhi': 'DEL',
  'new delhi': 'DEL',
  'bangkok': 'BKK',
  'city of angels': 'BKK',
  'hong kong': 'HKG',
  'fragrant harbor': 'HKG',
  'seoul': 'ICN',
  'beijing': 'PEK',
  'shanghai': 'PVG',
  'rio de janeiro': 'GIG',
  'rio': 'GIG',
  'sao paulo': 'GRU',
  'buenos aires': 'EZE',
  'lima': 'LIM',
  'bogota': 'BOG',
  'caracas': 'CCS',
  'johannesburg': 'JNB',
  'jo-burg': 'JNB',
  'cape town': 'CPT',
  'cairo': 'CAI',
  'casablanca': 'CMN',
  'lagos': 'LOS',
  'nairobi': 'NBO',
  'addis ababa': 'ADD',
  'melbourne': 'MEL',
  'perth': 'PER',
  'auckland': 'AKL',
  'wellington': 'WLG'
};

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};